# Generated by Django 4.0 on 2022-02-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
