# Generated by Django 4.0 on 2022-02-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_bookmarked_delete_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bookmarked',
            new_name='bookmarks',
        ),
    ]
