# Generated by Django 4.0 on 2022-02-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_avatar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='poster_avatar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.URLField(null=True),
        ),
    ]
